### ISSUE TITLE
Automatic subscription Discovery

### ISSUE THREAD

**Issue by chris-githubz** [F5Networks/f5-cloud-failover-extension#102]
## Do you already have an issue opened with F5 support?

C3833024, the issue is fixed, but this is a request that would get rid of the need for us to update the declaration every time a new subscription is created.

## Description

The way we've architected our Azure environment means we're creating a new subscription for each application, and each has a route table that requires updating via F5 CFE. This means we have to update the CFE declaration every time a new application is added to Azure.

If, instead, CFE could rely solely on the f5_cloud_failover_label tag on route tables to determine whether or not to update that route tables, we could forgo the subscription section of the declaration and CFE would just search every subscription it has access to.

## Environment information

Feature Enhancement

## Severity Level

Feature Enhancement

**Comment by shyawnkarim** [comment]
Thanks for submitting this issue. I've added this issue to our backlog so that it can be discussed by the team. Its being tracked internally with ID ESECLTPLT-3202.

**Comment by shyawnkarim** [comment]
Closing.

The F5 Cloud Failover Extension is now in Maintenance Mode, which means that we are not adding new capabilities and work is limited to bug fixes and needed maintenance. 

That being said, our team reviewed and scoped your request. After doing so, the team decided not implement this enhancement. 

If you still feel very strongly about this request, please reach out to me [via email](s.karim@f5.com) so that we can understand your situation better.
