### ISSUE TITLE
Allow CFE route failover for 0.0.0.0/0

### ISSUE THREAD

**Issue by fbchan** [F5Networks/f5-cloud-failover-extension#34]
I would like to have CFE to failover for a specific route table where both route appear on 2 different route table. Spun up a pair of F5 (3-NIC). There are external route table and internal route table. Both route table had 0.0.0.0/0 route. Both route table being tagged for route failover for other route.
External route table
-------------------
10.2.0.0/16 --> local
0.0.0.0/0 --> igw-xxxx
192.0.2.0/24 --> point to Active BIG-IP ENI-1234

Internal route table
-------------------
10.2.0.0/16 --> local
0.0.0.0/0 --> point to Active BIG-IP ENI-1234

Excerpt of the CFE declaration
 "range": "0.0.0.0/0",
        "nextHopAddresses": {
          "discoveryType": "static",
          "items": [
            "10.2.1.108",
            "10.2.2.228"
          ]
        }

As both route being tagged, during failover, CFE change both route table to point to ENI-1234, which not a desirable outcome. For 0.0.0.0/0 route, only require the internal route table to be failover. Not both.

**Comment by nmenant** [comment]
Hi,

Could you share your full CFE declaration. Have you tried the following: instead of doing Static discovery, you use RouteTag. This way for each route table you add another tag: f5_self_ips:<your IPs to failover>

for example: "f5_self_ips":"192.0.2.10,192.0.2.11"

this way you can setup which IPs should be used for failover in each route table

**Comment by fbchan** [comment]
My declaration
{
  "class": "Cloud_Failover",
  "controls": {
    "class": "Controls",
    "logLevel": "silly"
  },
  "environment": "aws",
  "externalStorage": {
    "scopingTags": {
      "f5_cloud_failover_label": "mydeployment"
    }
  },
  "failoverAddresses": {
    "scopingTags": {
      "f5_cloud_failover_label": "mydeployment"
    }
  },
  "failoverRoutes": {
    "scopingTags": {
      "f5_cloud_failover_label": "mydeployment"
    },
    "scopingAddressRanges": [
      {
        "range": "192.0.2.0/24",
        "nextHopAddresses": {
          "discoveryType": "static",
          "items": [
            "10.2.31.82",
            "10.2.32.23"
          ]
        }
      },
      {
        "range": "192.0.3.0/24",
        "nextHopAddresses": {
          "discoveryType": "static",
          "items": [
            "10.2.1.108",
            "10.2.2.228"
          ]
        }
      },
      {
        "range": "0.0.0.0/0",
        "nextHopAddresses": {
          "discoveryType": "static",
          "items": [
            "10.2.1.108",
            "10.2.2.228"
          ]
        }
      }
    ]
  },
  "schemaVersion": "1.3.0"
}

Will give it a try on the recommendation and will report back.

**Comment by vvt137** [comment]
I am affected by the same issue. I have tested the recommendation and it produced the same outcome. I.e. regardless whether I use discoveryType set to "static" (and selfIPs are listed as items) or to "f5_self_ips" (and selfIPs are listed under the AWS route table's tag "f5_self_ips"), CFE route failover still affects both route 192.0.2.0/24 pointing to F5 Elastic Interface and 0.0.0.0/0 originally pointing to an IGW or a NAT Gateway.

Here is my declaration:

    {
      "class": "Cloud_Failover",
          "controls":{
            "class":"Controls",
            "logLevel":"silly"
          },
      "environment": "aws",
      "externalStorage": {
        "scopingTags": {
          "f5_cloud_failover_label": "slb1"
        }
      },
      "failoverAddresses": {
        "enabled": true,
        "scopingTags": {
          "f5_cloud_failover_label": "slb1"
        }
      },
      "failoverRoutes": {
        "enabled": true,
        "scopingTags": {
          "f5_cloud_failover_label": "enabled"
        },
        "scopingAddressRanges": [
          {
            "range": "192.0.2.0/24",
            "nextHopAddresses": {
              "discoveryType": "static",
              "items": [
                "10.120.2.26",
                "10.120.3.60"
              ]
            }
          },
          {
            "range": "0.0.0.0/0",
            "nextHopAddresses": {
              "discoveryType": "routeTag"
            }
          }
        ]
      }
    }

**Comment by vvt137** [comment]
Is it possible to use different "scopingTags:f5_cloud_failover_label" values for different scopingAddressRanges parts of the declaration, so that different route tables work differently (even though API calls are made from the same F5 BIG-IP cluster)? 

I tried to insert different scopingTags clauses under scopingAddressRanges entries and it was successfully "declared" (no error message), but tests showed that only the "global" scopingTags value applied.

Here is what I have tried and only route tables with tag "slb1" were failing over (the shared route tables marked "enabled" were not failing over):

    {
      "class":"Cloud_Failover",
      "controls":{
        "class":"Controls",
        "logLevel":"silly"
      },
      "environment":"aws",
      "externalStorage":{
        "scopingTags":{
        "f5_cloud_failover_label":"slb1"
        }
      },
      "failoverAddresses":{
        "scopingTags":{
        "f5_cloud_failover_label":"slb1"
        }
      },
      "failoverRoutes":{
        "scopingTags": {
        "f5_cloud_failover_label": "slb1"
        },
        "scopingAddressRanges":[
             {
               "range":"192.0.2.0\/24",
               "scopingTags":{
                 "f5_cloud_failover_label":"enabled"
               }
             },
             {
               "range":"0.0.0.0/0",
               "scopingTags":{
                 "f5_cloud_failover_label":"slb1"
               }
             }
         ],
        "defaultNextHopAddresses":{
          "discoveryType":"static",
          "items":[
                "10.120.2.26",
                "10.120.3.60"
           ]
         }
       }
    }

**Comment by fbchan** [comment]
Yes. As with @vvt137 , similar outcome. I believe this due to the tags are global and it matches all 0.0.0.0/0.

**Comment by f5-chidambaram** [comment]
Hi, this has been added to our backlog, internal ID AUTOSDK-400.

**Comment by vvt137** [comment]
There is a way to make 0.0.0.0/0 failover for the "internal" or "server-facing" subnets only (whilst traffic from "external" or "client-facing" subnets to destination IPs within the "Private VIP" range like 192.0.2.0/24 is routed to and fails-over between the f5 external NICs/ENIs).

Let's assume the following settings of the AWS route tables:

*External AWS route table*
routes:
- 10.120.0.0/16 --> local
- 0.0.0.0/0 --> igw-xxxx
- 192.0.2.0/24 --> point to Active BIG-IP **External** eni-xxxx
tags:
- f5_cloud_failover_label: enabled
- f5_cloud_failover_vips: 1.1.1.1,1.1.1.2 (**dummy** IPs)

*Internal AWS route table*
routes:
- 10.120.0.0/16 --> local
- 0.0.0.0/0 --> point to Active BIG-IP **Internal** eni-xxxx
tags:
- f5_cloud_failover_label: enabled
- f5_cloud_failover_vips: 10.120.4.50,10.120.5.112 (selfIPs of BIG-IP **Internal** NICs)

(Note that "slb1" can be used instead of "enabled" as the value of the `f5_cloud_failover_label` tags of both route tables if there is only one F5 failover cluster within the VPC in question.)

Let's also assume that 10.120.2.26 and 10.120.3.60 are the selfIPs of BIG-IP **External** NICs.

Finally, we assume that both external and internal ENIs of the BIG-IPs are tagged with:
- f5_cloud_failover_label: slb1

(Note that current version of F5-supported AWS templates only add this tag to the "external" NIC, see https://github.com/F5Networks/f5-aws-cloudformation/issues/124)

The following declaration would then produced the desired behaviour of the cluster:

    {
        "class":"Cloud_Failover",
        "controls":{
          "class":"Controls",
          "logLevel":"debug"
        },
        "environment":"aws",
        "externalStorage":{
          "scopingTags":{
          "f5_cloud_failover_label":"slb1"
          }
        },
        "failoverAddresses":{
          "scopingTags":{
          "f5_cloud_failover_label":"slb1"
          }
        },
        "failoverRoutes":{
          "scopingTags":{
          "f5_cloud_failover_label":"enabled"
          },
          "scopingAddressRanges":[
               {
                 "range":"192.0.2.0\/24",
                 "nextHopAddresses": {
                   "discoveryType": "static",
                   "items": [
                      "10.120.2.26",
                      "10.120.3.60"
                   ]
                 }
               },
               {
                 "range":"0.0.0.0\/0",
                 "nextHopAddresses": {
                   "discoveryType": "routeTag"
                 }
               }
           ]
         }
    }

Admittedly, this approach may be considered too risky for some environments. My main concern is that someone may decide to "fix" the "dummy" values of the f5_cloud_failover_vips tag by replacing them with the "thought to be correct" selfIP addresses of any of the existing F5 clusters within the VPC. After such a "fix" is implemented the next failover event within that cluster will break routing to 0.0.0.0/0 for all "external AWS route tables" in question. Another concern I have is that this approach is not documented in https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/, so it is possible that next updates to CEF may break this functionality.

However, it may be an acceptable temporary measure assuming F5 is going modify the CEF so that different `scopingAddressRanges` would work as expected when they are configured with different "f5_cloud_failover_label" values (as discussed in my "12 Jul update above).

**Comment by nmenant** [comment]
@f5-chidambaram multiple scoping range has been implemented with 1.5

Please see https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/example-declarations.html#aws for some examples

Please Close

**Comment by shyawnkarim** [comment]
Closing.

This issue was resolved with [Release 1.5](https://github.com/F5Networks/f5-cloud-failover-extension/releases/tag/v1.5.0).
