### ISSUE TITLE
CFE uses hostname rather than device name when identifying traffic group

### ISSUE THREAD

**Issue by alaari-f5** [F5Networks/f5-cloud-failover-extension#4]
(Issue moved from https://github.com/f5devcentral/f5-cloud-failover-extension/issues/23)
Reported By: @C0missar 

If the host name of the device does not match the device name in the device group, CFE is unable to identify itself and determine which traffic groups are associated. The result is that both devices think they are in standby, both report themselves as being in standby in response to a call to /mgmt/shared/cloud-failover/inspect, and no EIP re-association ever occurs.

The host name is written to the S3 f5cloudfailoverstate.json file, and the failover script searches for this name in the device group.

The CFE should only use the device name for identification of the traffic groups.

**Comment by alaari-f5** [comment]
Thanks for reporting this bug. I've created internal ID AUTOSDK-262 to get this fixed.

**Comment by alaari-f5** [comment]
Any guess on when we'll see a fix?  I'm trying to determine how much effort to put in to a workaround.

There is one other CFT issue that would be very helpful to see addressed in the official released CFT, and that is issue #74.  I'm not sufficiently familiar with CFTs to know how to code these ready tests, and it seems to me that everyone would want the same things:


  *   Licensed
  *   Config loaded
  *   REST interface up
  *   Config UI running

There are other things that some people might want to check, but it seems to me that at a minimum, if any of these are not true, then we don't have a useful instance yet.

Thanks,

Stan Ward
IT Application Security Architect
The Sherwin-Williams Company
Cell: 937.344.8342
Stan.Ward@Sherwin.com<mailto:michael.s.tetreault@sherwin.com>
http://www.sherwin-williams.com<http://www.sherwin-williams.com/>

**Comment by alaari-f5** [comment]
I can give you an update once this bug has been prioritized for a sprint.

**Comment by shyawnkarim** [comment]
@C0missar is there a specific requirement that the hostnames do not match?

**Comment by C0missar** [comment]
No, just the opposite - I want them to match.  But when I change the hostname from the default assigned when the CFT is executed, such as 'ip-10-195-201-249.ebus.swaws' to 'awsf5proda.sherwin.com', the device name does not change, and it cannot be changed without breaking device trust first and then rebuilding it.

The problem then is that the CFE uses the host name to identify the HA members, but the traffic group is defined in terms of the device name, so HA can never work unless the two names match.  This is a bug in CFE.  You shouldn't have to fail over the entire device, just a single device group; besides, I don't KNOW the name of the device to build the declaration without more calls to find it.

There should also be some indication of CFE failure.  Upon triggering, CFE will happily report that it has failed over, when no change has occurred to either the device state, the state file, or the EIP associations.

As a general rule, I think the host name and device name SHOULD match; otherwise, it's confusing operationally, if nothing else.  As a separate issue, there should be a way to specify the host name in the CFT so that there is no need to manually change the device name.  The  amount of code that it takes to change the host name becomes ridiculous if the device name must be changed as well - break trust, change host name A, change device name A, change host name B, change device name B, rebuild trust.

Thanks,
Stan

**Comment by shyawnkarim** [comment]
@C0missar, thanks for this additional clarity. I've added these notes to our ticket, internal ID AUTOSDK-262.

**Comment by shyawnkarim** [comment]
@C0missar, AUTOSDK-262 has been scheduled for our next sprint, which starts tomorrow.

**Comment by shyawnkarim** [comment]
Closing.

@C0missar work on this issue has been completed and will be included in the next release on May 28, 2020.

Please feel free to reopen this issue if you still run into problems with this.
