### ISSUE TITLE
GCE API based failover template issue

### ISSUE THREAD

**Issue by jbaribeault** [F5Networks/f5-cloud-failover-extension#47]
The GCE API-based failover templates refer to a link to download the failover plugin via the github releases, whereas the rest of the downloads occur from cdn.f5.com; this makes it tough for locked down internet access to be opened up.

`'curl -s -f --retry 20 -o /config/cloud/f5-cloud-libs.tar.gz https://cdn.f5.com/product/cloudsolutions/f5-cloud-libs/v4.22.0/f5-cloud-libs.tar.gz',
                                    'curl -s -f --retry 20 -o /config/cloud/f5-cloud-libs-gce.tar.gz https://cdn.f5.com/product/cloudsolutions/f5-cloud-libs-gce/v2.6.0/f5-cloud-libs-gce.tar.gz',
                                    'curl -s -f --retry 20 -o /config/cloud/f5-appsvcs-3.20.0-3.noarch.rpm https://cdn.f5.com/product/cloudsolutions/f5-appsvcs-extension/v3.20.0/f5-appsvcs-3.20.0-3.noarch.rpm',
                                    'curl -s -f -L --retry 20 -o /config/cloud/f5-cloud-failover-1.4.0-0.noarch.rpm https://github.com/F5Networks/f5-cloud-failover-extension/releases/download/v1.4.0/f5-cloud-failover-1.4.0-0.noarch.rpm',`

The script has a -L on the last "curl" for a reason, to follow the 302 from github to wherever that may lead - 2 problems with that:
1. If someone were to allow access to all of github to even get the link to follow; that's pretty wide open and 
2. The location header can change: sometimes github serves from its' own domain, sometimes from an S3 bucket, likely sometimes somewhere else. 

When these scripts fail to download one of the files during the initial boot; they get stuck in a neverending loop.

Any chance of getting the release tarballs published to the F5 CDN?

**Comment by f5-chidambaram** [comment]
Hi, this has been added to Cloud Templates backlog, tracking ID ESECLDTPLT-2203

**Comment by shyawnkarim** [comment]
Closing due to age. Our [v1 legacy templates](https://github.com/F5Networks/f5-google-gdm-templates) are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2). Additionally, our v2 templates use [Runtime-Init](https://github.com/F5Networks/f5-bigip-runtime-init) to download Automation Toolchain packages, use the GitHub locations, and URLs can be customized.
