### ISSUE TITLE
GCP issue if multiple project are involved

### ISSUE THREAD

**Issue by llomgui** [F5Networks/f5-cloud-failover-extension#83]
Hello,

We have 2 projects, one project is dedicated to network (VPC), the other one is for instances, service account, roles, target instances, forwarding roles.

The issue is for the route, we are forced to create it in network's project to match with a VPC.
In you code, you don't handle this case.

We are getting an error "cant find definition on indefined" https://github.com/F5Networks/f5-cloud-failover-extension/blob/master/src/nodejs/providers/gcp/cloud.js#L921

The main cause is : https://github.com/F5Networks/f5-cloud-failover-extension/blob/master/src/nodejs/providers/gcp/cloud.js#L262

It's looking for the route inside the same project.

**Comment by shyawnkarim** [comment]
Thanks for submitting your issue. We are now tracking your request internally with ID AUTOSDK-566.

**Comment by shyawnkarim** [comment]
Closing.

Cloud Failover Extension is now in maintenance mode. Only critical bugs, CVEs, and security updates will be taken into consideration for updating CFE.

If this issue is still important to you, please email me directly at [s.karim@f5.com](s.karim@f5.com) and provide me with details around your situation.
